[theme]
primaryColor = "#1769FF"
backgroundColor = "#F5F9FE"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#10213D"
font = "serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
enableStaticServing = true

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
